PR: 이모지 통계 Slash 커맨드기능 구현
ks0927/CH_Bot pull request #1
Opened 2023-12-02 07:52 UTC by ks0927

### PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 반영 브랜치
feat/EmojiStatistics -> dev

### 변경 사항
이모지 통계 Slash 커맨드기능 추가

2023-12-02 16:36 UTC, Libienz requested changes
하이 😃

먼저 고생했다 

너가 나한테 설명한 문제점을 프로그래밍을 통해서 해결하고자 노력했고 작은 버전을 빠르게 만들어서 빠른 피드백을 받을 수 있도록 한 점이 좋네 🤗

다만 해당 프로그램이 어떤 도메인을 다루고 어떤 문제점을 해결하는지 문서 작업이 (ex: README.md)미흡한 점이 아쉽고 기능 구현에 있어 테스트가 동반되지 않은 점은 아쉬워

또한 기능 분리, 컨벤션, 레이어 책임 관련해서 리팩토링할 부분들도 있는 것 같아서 리뷰 남겨본다 😄

작업 꾸준히 진행하면서 좋은 경험하길 바래 😎

2023-12-02 16:36 UTC, Libienz commented on src/main/java/CyberHanryang/ChBotApplication.java
> +		}
챗봇의 설정을 불러오고 서비스를 준비하는 부분인 것 같은데 메서드로 분리하여 가독성을 향상시킬 수 있을 것 같다 🤔

2023-12-02 16:36 UTC, Libienz commented on src/main/java/CyberHanryang/dto/EmojiStatDto.java
> +
이모지 통계 Dto는 이모지와 이모지가 사용된 count를 가지고 있네

다만 현재 이모지는 엔티티인데 엔티티를 그대로 dto안에 포장시키고 있는부분이 걸린다.
dto를 사용하는 이유는 레이어간 정보를 교환할 때 부수 효과 (side effect)를 방지하고 엔티티 스펙을 외부에 노출시키지 않기 위함인데 이처럼 사용하면 앞서 말한 효과가 미미해지겠네

emoji 엔티티와 연관된 (혹은 api에 종속적인) dto ```EmojiDto```등이 추가되어야 하지 않나 생각이 든다 😃

2023-12-02 16:36 UTC, Libienz commented on src/main/java/CyberHanryang/entity/Emoji.java
> +    }
정적 팩토리 메서드로 Emoji를 생성하는 부분이네

우선 정적 팩토리 메서드를 사용하려면 해당 엔티티의 기본 생성자를 막음으로써 생성 로직을 일관되도록 수정해줘야 할 것 같다.

또 정적 팩토리 메서드의 네이밍 컨벤션을 다르게 바꾸어봐도 좋을 것 같아
파라미터 여러개를 통해 생성하는 경우는 ```of```를 사용하고 파라미터 하나를 통해 생성하는 경우는 ```from```을 사용한다와 같은 이미 정해진 컨벤션을 도입하는 것도 괜찮아 보이네

2023-12-02 16:36 UTC, Libienz commented on src/main/java/CyberHanryang/listener/EmojiStatusSlashCommand.java
> +}
슬래시 커맨드를 감지하고 서비스하도록 유도하는 listener 부분인 것 같네 😃

역할과 책임의 더 철저히 분리될 수 있을 것 같다는 개인적인 생각이야

현재 ```리스너```는 이벤트를 감지하고 해당 이벤트에 대한 서비스까지 한번에 수행하고 있지만 리스너는 이벤트를 감지하는 것만 열심히하고 해당 이벤트를 위해 서비스하는 클래스는 서비스 레이어에 별도로 위치 시킴으로써 유지보수가 더욱 용이한 코드가 되지 않을까 하는 생각이다

이렇게 분리한 후에 객체지향 생활체조 원칙을 고려해서 한 메서드가 하나의 일만 하도록 분리해보는 작업도 추천할께

2023-12-02 16:36 UTC, Libienz commented on src/main/java/CyberHanryang/listener/MessageListener.java
> +
마찬가지로 해당 ```리스너```도 ```감지```와 ```서비스```를 나누어서 설계하도록 권유한다 😁

보면 볼수록 리스너가 컨트롤러의 역할을 수행해야 한다고 생각이 들어
컨트롤러의 역할을 생각해보고 리스너가 어떤 일을 수행해야 하는지 한번 생각해보는 것이 좋을 것 같다 🤗

2023-12-02 16:36 UTC, Libienz commented on src/main/java/CyberHanryang/service/EmojiService.java
> +    }
emoji의 통계를 말아주는 메서드네 🤔

메서드는 통계를 말아준다는 하나의 일을 수행하는 것 처럼 이해될 수도 있지만 내가 보기에는 여기에서도 분리의 여지가 많은 것 같다 🙂

모든 이모지의 count가 0인 List를 생성하는 부분도 하나의 메서드로 분리될 수 있을 것 같고

레포지토리 레이어에서 이모지 통계를 가져온 후에 하나씩 대입하는 부분도 하나의 메서드로 분리될 수 있을 것 같고

각각을 dto로 변환하는 부분도 하나의 메서드로 수정될 수 있을 것 같다.
 
각각을 private 메서드로 정의하고 반영하면 service로직의 이해도를 높일 수 있을 뿐더러 수정 지점을 파악하고 확장하는데에 있어 편리해질 것이라고 생각해 🙂

또 private 메서드를 생성하고 난 후에는 각각의 역할이 클래스의 책임에 부합하는지 , 별도의 서비스 클래스, 혹은 util 클래스로 분리가능한지도 한 번 고민해보면 좋을 것이라고 생각한다😊

2023-12-02 16:36 UTC, Libienz commented on src/main/java/CyberHanryang/config/BotConfig.java
> +
디스코드 api를 사용하는 토큰이네 토큰은 민감한 정보로 원격 저장소에서 관리되어야 하는 정보는 아닌 것 같네. 

야물 파일로 관리하면서 gitignore를 통해 secret하게 관리하는 것을 추천한다 😄

그리고 한번 노출이 된 이상 새로운 키를 발급받아야겠네 🤔

2023-12-02 16:36 UTC, Libienz commented on src/main/java/CyberHanryang/entity/Emoji.java
> +    }
다른 엔티티에서도 동일한 부분 확인했으니까 해당 부분은 모든 엔티티에서 검토 해봐야 할 것 같음!

2023-12-02 16:36 UTC, Libienz commented on src/main/java/CyberHanryang/listener/EmojiStatusSlashCommand.java
> +
어떤 식으로 formating 할지까지 리스너에 들어 있네 

리스너는 이벤트를 감지하고 이벤트 관련 서비스 실행을 위임시키는 역할만 수행하도록 책임을 분리한다면 
해당 로직은 뷰로직으로 분리할 수 있을 것 같음 🤔

클래스 역할과 책임 관련해서 철저히 생각해보아야 할 것 같아

2023-12-03 00:56 UTC, ks0927 commented on src/main/java/CyberHanryang/dto/EmojiStatDto.java
> +
동의합니다. Api에 종속적인 EmojiDto를 따로 만들어야겠습니다!

2023-12-03 01:01 UTC, ks0927 commented on src/main/java/CyberHanryang/service/EmojiService.java
> +    }
생각해보니 충분히 분리의 여지가 있는 것 같습니다!

2023-12-03 01:03 UTC, ks0927 commented on src/main/java/CyberHanryang/config/BotConfig.java
> +
gitignore과 yml 파일을 통해 secret하게 관리 해보겠습니다~ 토큰은 새로 발급 받았습니다!

2024-04-16 14:40 UTC, closed without merging